--liquibase formatted sql

-- ─────────────────────────────────────────────────────────────────────────────
-- Reusable trigger function: sets updated_at = now() on every UPDATE.
-- Created once, applied to any table that needs it.
-- ─────────────────────────────────────────────────────────────────────────────
--changeset digitaltwin:004-updated-at-function splitStatements:false
CREATE OR REPLACE FUNCTION blockchain_schema.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--rollback DROP FUNCTION blockchain_schema.set_updated_at();


-- ─────────────────────────────────────────────────────────────────────────────
-- transactions — one row per blockchain operation requested
--
-- id          : UUIDv7 — monotonic, time-sortable, generated by Java
-- request_id  : caller-supplied idempotency key (UNIQUE); if the same
--               request_id arrives again, the existing row is returned
-- wallet_id   : source wallet (FK → wallets); null for watch-only queries
-- to_address  : destination address on the blockchain
-- amount      : raw units (lamports for SOL, micro-units for SPL tokens)
-- token_mint  : null = native asset (SOL); set for SPL token transfers
-- blockchain_id: which chain (FK → blockchains)
-- status      : PENDING → SUBMITTED → CONFIRMED | FAILED
-- tx_hash     : blockchain transaction signature, set after submission
-- error_message: set on FAILED
-- ─────────────────────────────────────────────────────────────────────────────
--changeset digitaltwin:004-create-transactions
CREATE TABLE blockchain_schema.transactions (
    id              UUID         PRIMARY KEY,
    request_id      UUID         NOT NULL,
    wallet_id       UUID         REFERENCES blockchain_schema.wallets(id),
    blockchain_id   VARCHAR(20)  NOT NULL REFERENCES blockchain_schema.blockchains(id),
    to_address      TEXT         NOT NULL,
    amount          BIGINT       NOT NULL,
    token_mint      TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                        CONSTRAINT chk_status CHECK (status IN ('PENDING','SUBMITTED','CONFIRMED','FAILED')),
    tx_hash         TEXT,
    error_message   TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_request_id UNIQUE (request_id)
);

CREATE TRIGGER trg_transactions_updated_at
    BEFORE UPDATE ON blockchain_schema.transactions
    FOR EACH ROW EXECUTE FUNCTION blockchain_schema.set_updated_at();
--rollback DROP TABLE blockchain_schema.transactions;
