services:
  schemaspy:
    image: schemaspy/schemaspy
    volumes:
      - ../public/erd:/output
    command: >
      -t pgsql11
      -host ${DB_HOST}
      -port ${DB_PORT}
      -db ${DB_NAME}
      -u ${DB_USERNAME}
      -p ${DB_PASSWORD}
      -s ${DB_SCHEMA}
    network_mode: host
