--liquibase formatted sql

-- ─────────────────────────────────────────────────────────────────────────────
-- wallet_creation_requests — tracks every "create me a wallet" request
--
-- Idempotency: (request_id, blockchain_id) is UNIQUE.
-- If the same pair arrives again, return the stored public_address immediately.
--
-- id            : UUIDv7 — monotonic, generated by Java
-- request_id    : caller-supplied idempotency key
-- blockchain_id : which chain was requested
-- seed_group_id : which seed group was used (audit trail)
-- derivation_index: which index was claimed (audit trail)
-- public_address: the resulting address — stored for reconciliation
-- status        : PENDING → FULFILLED | FAILED
-- ─────────────────────────────────────────────────────────────────────────────
--changeset digitaltwin:006-create-wallet-creation-requests
CREATE TABLE blockchain_schema.wallet_creation_requests (
    id                UUID        PRIMARY KEY,
    request_id        UUID        NOT NULL,
    blockchain_id     VARCHAR(20) NOT NULL REFERENCES blockchain_schema.blockchains(id),
    seed_group_id     UUID        REFERENCES blockchain_schema.seed_groups(id),
    derivation_index  INTEGER,
    public_address    TEXT,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                          CONSTRAINT chk_wcr_status CHECK (status IN ('PENDING','FULFILLED','FAILED')),
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_wcr_request UNIQUE (request_id, blockchain_id)
);

CREATE TRIGGER trg_wcr_updated_at
    BEFORE UPDATE ON blockchain_schema.wallet_creation_requests
    FOR EACH ROW EXECUTE FUNCTION blockchain_schema.set_updated_at();
--rollback DROP TABLE blockchain_schema.wallet_creation_requests;
